Traceback (most recent call last):
  File "test.py", line 218, in <module>
    predictions, labels, class_names, classes = range(num_classes) )
TypeError: get_auc() got multiple values for argument 'classes'
