mkdir: cannot create directory ‘experiments’: File exists
Traceback (most recent call last):
  File "train.py", line 486, in <module>
    val_predictions, val_labels = aggregate(data['valid'].filenames, method=opt.method)
  File "train.py", line 326, in aggregate
    probabilities = prob_v(tile_paths)
  File "/share/apps/numpy/1.13.1/python3.5/intel/lib/python3.5/site-packages/numpy-1.13.1-py3.5-linux-x86_64.egg/numpy/lib/function_base.py", line 2734, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/share/apps/numpy/1.13.1/python3.5/intel/lib/python3.5/site-packages/numpy-1.13.1-py3.5-linux-x86_64.egg/numpy/lib/function_base.py", line 2810, in _vectorize_call
    outputs = ufunc(*inputs)
  File "train.py", line 269, in get_tile_probability
    with open(tile_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/beegfs/sb3923/DeepCancer/alldata/lung_smoke_stage/Luad_stage/Luad_stageTilesSortedstage-3/valid_TCGA-05-4418-01A-01-TS1.61b48f7c-970a-4cd9-87f7-b2da39b58842_11_3.jpeg'
